#pragma once

/* key matrix size */
// Rows are doubled-up
#define MATRIX_ROWS 10
#define MATRIX_COLS 6

/* COL2ROW or ROW2COL */

/* Serial communication pins */
/* USART Half-duplex */
#define SERIAL_USART_TX_PIN GP1

#define AUTO_SHIFT_TIMEOUT 200
#define NO_AUTO_SHIFT_TAB
#define NO_AUTO_SHIFT_ALPHA

#define EE_HANDS

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE

#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL RGBLIGHT_MODE_RAINBOW_SWIRL + 2
#define RGBLIGHT_EFFECT_SNAKE RGBLIGHT_MODE_SNAKE + 3
#define RGBLIGHT_EFFECT_TWINKLE RGBLIGHT_EFFECT_TWINKLE + 4
#define RGBLIGHT_EFFECT_RAINBOW_MOOD RGBLIGHT_MODE_RAINBOW_MOOD + 3
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_STATIC_GRADIENT

#define LEADER_PER_KEY_TIMING
#define LEADER_NO_TIMEOUT
// https://github.com/qmk/qmk_firmware/blob/master/docs/tap_hold.md
// #define PERMISSIVE_HOLD_PER_KEY

// Reset
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
// #define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
// #define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_WINCOMPOSE, UNICODE_MODE_MACOS
